import { ReactNode } from 'react'

export const metadata = {
  title: 'Auth',
  description: 'Generated by create next app',
}

export default function AuthLayout({ children }: { children: ReactNode }) {
  return <main>{children}</main>
}
